### ISSUE TITLE
Web3 Talk #24: “Gaming and Extended Reality in Web3"

### ISSUE THREAD

**Issue by znerual56** [blockchainweek/data#51]
Please use this template to suggest a new event or update an existing event for the BBW website! You can also directly [submit your event as a pull request](https://github.com/blockchainweek/data/tree/main/data/24/events) to this repository. This will speed up things significantly!

```toml
name = "Web3 Talk #24: Gaming and Extended Reality in Web3"

shortname = "Gaming & XR in Web3"

types = ["meetup"]

status = "published"

org = "DAO.Researcher"

dri = "znerual56"

poc = "Laurenz L., +491732624511, mailto:l.lenkewitz@gmail.com"

date = "2024-05-27"

days = 1

times = "19:00-21:00"

venueName = "Spreegold Bikini Berlin, 1st floor, Co-working area"

venueUrl = "https://maps.app.goo.gl/BYG9che6WyB6XCCCA?g_st=ic"

venueAddress = "Budapester Str. 50, 10787 Berlin"

languages = ["english"]

attendees = 150

chains = []

tags = ["gaming", "xr", "metaverse", "extendedreality"]

logo = "
<img width="394" alt="DaoResearcherLogo jpg" src="https://github.com/blockchainweek/data/assets/168823098/f32dfe7b-a51d-4948-9048-e0693af81d0f">
"

description = """Gamers welcome! Connect to like-minded enthusiasts from Berlin's creative Web3-, Metaverse, AI, and Blockchain scene!
For years, the Web3 space discussed how Blockchain could support gaming, and how the gaming industry could make use of AI, XR (Extended Reality), and the Metaverses. Slowly, the games industry adopted Web3 and AI technologies, and Apple launched Vision Pro. We will discuss the latest trends with industrie insiders and take a look at the future of artificial intelligence in games, and games in the Metaverses. Our speakers:
+ CEO of a games company
+ CTO of a XR company
+ Lawyer and gaming industry consultant
+ Games magazine journalist
"""

[cfp]
link = "https://linktr.ee/Laurenz_L"

[registration]
type = "signup"

price = "0 EUR"

link = "http://bit.ly/Gaming-and-XR"

button = "Sign up for free here!"

status = "available"

[links]
web = "http://bit.ly/Gaming-and-XR"

docs = "https://daoResearcher.org/"

```

**Comment by kuzdogan** [comment]
Your event is live please double check if everything is correct :) https://blockchainweek.berlin/24

**Comment by znerual56** [comment]
Hi Kaan, thank you so much!
Just one little correction: 
The venueUrl is https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=5354555535&class=amenity 

(currently it links to Jim Block, but it should link to Spreegold)

**Comment by znerual56** [comment]
Hi Kaan, thank you so much!

Just one little correction:
The venueUrl is
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=5354555535&class=amenity

(currently it links to Jim Block, but it should link to Spreegold)


---
Laurenz L.
DAO.Researcher
https://linktr.ee/Laurenz_L


Kaan Uzdoğan ***@***.***> schrieb am So. 5. Mai 2024 um 19:15:

**Comment by kuzdogan** [comment]
Fixed with https://github.com/blockchainweek/data/commit/1f224807374c676fa2dd490c6efabf227d25c826

**Comment by znerual56** [comment]
Hi Kaan, 
really sorry to bother you again, but the venueUrl is https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=5354555535&class=amenity    otherwise it still shows Jim Burger instead of Spreegold.

Sorry, that was my fault.

**Comment by znerual56** [comment]
Hi Kaan,
really sorry to bother you again, but the venueUrl is
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=5354555535&class=amenity
otherwise
it still shows Jim Burger instead of Spreegold.

Sorry, that was my fault.




---
Laurenz L.
DAO.Researcher
https://linktr.ee/Laurenz_L


Kaan Uzdoğan ***@***.***> schrieb am Mo. 6. Mai 2024 um 08:59:

**Comment by kuzdogan** [comment]
Not sure if I understand.

I've updated the link. Can you please check the current live version if it's correct?

**Comment by znerual56** [comment]
Now it's perfect! Thanks again!  🙏

**Comment by znerual56** [comment]
How can I update the description? (I would like to add names of speakers)

**Comment by kuzdogan** [comment]
> How can I update the description? (I would like to add names of speakers)

Please open a PR to change https://github.com/blockchainweek/data/blob/main/data/24/events/web3-talk/index.toml

**Comment by znerual56** [comment]
Hello Kaan,

I can't edit the code which is shown on
https://github.com/blockchainweek/data/blob/main/data/24/events/web3-talk/index.toml

The description should be edited as follows:

"""
Gamers welcome! Connect to like-minded enthusiasts from Berlin's creative
Web3-, Metaverse, AI, and Blockchain scene! For years, the Web3 space
discussed how Blockchain could support gaming, and how the gaming industry
could make use of AI, XR (Extended Reality), and the Metaverses. Slowly,
the games industry adopted Web3 and AI technologies, and Apple launched
Vision Pro. We will discuss the latest trends with industrie insiders and
take a look at the future of AI and XR in games, and games in the
Metaverses.
Our speakers:
+ Nicola Mizon, founder, VIZTA Digital
+ Florian Dreschner, CTO, VOYA Games
+ Prof. Dr. Malte Behrmann, lawyer, former speaker of German Games
Association
"""


Thank you!

---
Laurenz L.
DAO.Researcher
https://linktr.ee/Laurenz_L


Kaan Uzdoğan ***@***.***> schrieb am Mo. 13. Mai 2024 um
20:48:

**Comment by kuzdogan** [comment]
Updated, please double check at https://blockchainweek.berlin/24
